### ISSUE TITLE
some scripts require Python2

### ISSUE THREAD

**Issue by rhaas80** [BenMql/coral#12] opened 2021-03-20 02:18 UTC
Most scripts seem to work with both Python3 and Python2. However the `dealiase_volumes.py` script seems to assume Python2 and produces errors like this when used with Python3 on the First_Run data:

```
data/plane_layer$ python3 dealiase_volumes.py test1/
[ 001/702 ] :: test1//Volumes/linear_var01_time00000100_full.dat
Traceback (most recent call last):
  File "coral/data/plane_layer/dealiase_volumes.py", line 57, in <module>
    clean_this_dir(directory_to_clean)
  File "coral/data/plane_layer/dealiase_volumes.py", line 52, in clean_this_dir
    dumm_integer = read_and_deAlias(root, my_file)
  File "coral/data/plane_layer/dealiase_volumes.py", line 28, in read_and_deAlias
    aux2 = np.delete(aux1, np.arange(NXAA/3+1,2*NXAA/3+1) , axis = 1)
  File "<__array_function__ internals>", line 5, in delete
  File "/usr/lib/python3/dist-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type
```

This dependency on a particular (also no longer supported) Python version should be documented, yet I cannot find it mentioned in the wiki or documentation.

**Comment by rhaas80** [comment] 2021-03-30 02:36
and at least one documentation page (https://github.com/BenMql/coral/wiki/4_Data_visualisation#user-content-colorplot-with-colorplot_slicepy) uses Python3.

**Comment by BenMql** [comment] 2021-05-18 15:51
Roland,
 
This is a valid point. It is true that old helper routines are written in python2, whereas those added recently are (and any future addition will be) python3. I am in the process of translating everything to python3. 

For this specific routine, division was to blame. I have replaced `/` with `//` and included `from __future__ import division` at the top so that it runs with both python2 and python3

**Comment by rhaas80** [comment] 2021-08-11 14:37
Should I close the ticket? You seem to have addressed the issue raised.

**Comment by BenMql** [comment] 2021-08-30 10:41
> Should I close the ticket? You seem to have addressed the issue raised.

I was unsure about the etiquette concerning issues. (More specifically, should the author of the issue be the sole judge of whether the issue should be closed or not?) I was cautious not to overstep my prerogatives. As you said, the issue is addressed and I'll close this ticket.

**Closed as completed by BenMql** 2021-08-30 10:41 UTC
